Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

# MySQL Exercise 7: Joining Tables with Inner Joins

Before completing these exercises, I strongly recommend that you watch the video called "What are Joins?" that describe what joins are, and how different types of joins work.

As one of the last building blocks we need to address our Dognition analysis questions, in this lesson we will learn how to combine tables using inner joins.

   
## 1. Inner Joins between 2 tables

To begin, load the sql library, connect to the Dognition database, and set the Dognition database as the default.

In [4]:
%reload_ext sql
%sql mysql://studentuser:studentpw@mysqlserver/dognitiondb 
%sql USE dognitiondb

0 rows affected.


[]

Recall that tables in relational databases are linked through primary keys and sometimes other fields that are common to multiple tables (as is the case with our Dognition data set).  Our goal when we execute a JOIN or make a joined table is to use those common columns to let the database figure out which rows in one table match up to which rows in another table.  Once that mapping is established using at least one common field or column, the database can pull any columns you want out of the mapped, or joined, tables and output the matched data to one common table.

An inner join is a join that outputs only rows that have an exact match in both tables being joined:

<img src="https://duke.box.com/shared/static/xazeqtyq6bjo12ojvgxup4bx0e9qcn5d.jpg" width=400 alt="INNER_JOIN" />

To illustrate how this works, let's find out whether dog owners that are particularly surprised by their dog's performance on Dognition tests tend to own similar breeds (or breed types, or breed groups) of dogs.  There are many ways to address this question, but let's start by focusing on the dog owners who provided at least 10 ratings for one or more of their dogs in the ratings table. Of these owners, which 200 owners reported the highest average amount of surprise at their dog's performance, and what was the breed, breed_type, and breed_group of each of these owner's dog?

The surprise ratings are stored in the reviews table.  The dog breed information is provided in the dogs table.  There are two columns that are common to both tables: user_guid and dog_guid. How do we use the common columns to combine information from the two tables? 

To join the tables, you can use a WHERE clause and add a couple of details to the FROM clause so that the database knows from what table each field in your SELECT clause comes.  

First, start by adding all the columns we want to examine to the SELECT statement:

```mySQL
SELECT dog_guid AS DogID, user_guid AS UserID, AVG(rating) AS AvgRating, 
       COUNT(rating) AS NumRatings, breed, breed_group, breed_type
```
then list all the tables from which the fields we are interested in come, separated by commas (with no comma at the end of the list):

```mySQL
FROM dogs, reviews
```
then add the other restrictions:

```mySQL
GROUP BY user_guid, dog_guid, breed, breed_group, breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query and see what happens:**



In [7]:
%%sql
SELECT dog_guid AS DogID, user_guid AS UserID, 
AVG(rating) AS AvgRating, 
COUNT(rating) AS NumRatings, breed, breed_group, breed_type
FROM dogs, reviews
GROUP BY user_guid, dog_guid, breed, breed_group, breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200

(_mysql_exceptions.OperationalError) (1052, "Column 'dog_guid' in field list is ambiguous") [SQL: 'SELECT dog_guid AS DogID, user_guid AS UserID, \nAVG(rating) AS AvgRating, \nCOUNT(rating) AS NumRatings, breed, breed_group, breed_type\nFROM dogs, reviews\nGROUP BY user_guid, dog_guid, breed, breed_group, breed_type\nHAVING NumRatings >= 10\nORDER BY AvgRating DESC\nLIMIT 200']


You should receive an error message stating that the identity of dog_guid and user_guid in the field list is ambiguous. The reason is that the column title exists in both tables, and MySQL doesn't know which one we want. We have to specify the table name before stating the field name, and separate the two names by a period <mark>(NOTE: read this entire section before deciding whether you want to execute this query)<mark\>:

```mySQL
SELECT dogs.dog_guid AS DogID, dogs.user_guid AS UserID, AVG(reviews.rating) AS AvgRating,     
       COUNT(reviews.rating) AS NumRatings, dogs.breed, dogs.breed_group, dogs.breed_type
FROM dogs, reviews
GROUP BY dogs.user_guid, dogs.dog_guid, dogs.breed, dogs.breed_group, dogs.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```


You can also take advantage of aliases so that you don't have to write out the name of the tables each time.  Here I will introduce another syntax for aliases that omits the AS completely.  In this syntax, the alias is whatever word (or phrase, if you use quotation marks) follows immediately after the field or table name, separated by a space. Some people find it easier to read queries if you use the syntax without an AS to create table aliases, but retain the syntax with an AS to create field aliases (but both syntaxes work for field aliases and table aliases).  So we could write:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
GROUP BY DogID, UserID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

I am tempted to tell you to run this query so that you will see what happens, but instead, I will explain what will happen and let you decide if you want to see what the output looks...and feels...like.  
      
There is nothing built into the database table definitions that can instruct the server how to combine the tables on its own (remember, this is how relational databases save space and remain flexible).  Further, the query as written does not tell the database how the two tables are related.  As a consequence, rather than match up the two tables according to the values in the user_id and/or dog_id column, the database will do the only thing it knows how to do which is output every single combination of the records in the dogs table with the records in the reviews table.  In other words, every single row of the dogs table will get paired with every single row of the reviews table.  This is known as a Cartesian product.  Not only will it be a heavy burden on the database to output a table that has the full length of one table multiplied times the full length of another (and frustrating to you, because the query would take a very long time to run), the output would be close to useless.

To prevent this from happening, tell the database how to relate the tables in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

To be very careful and exclude any incorrect dog_guid or user_guid entries, you can include both shared columns in the WHERE clause:

```mySQL
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating, 
       COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid=r.dog_guid AND d.user_guid=r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >= 10
ORDER BY AvgRating DESC
LIMIT 200
```

**Try running this query now:**

In [8]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating,
COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid = r.dog_guid AND d.user_guid = r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
HAVING NumRatings >=10
ORDER BY AvgRating DESC
LIMIT 200

38 rows affected.


[('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fdc09a82-7144-11e5-ba71-058fbc01cf0b', 'ce99bb12-7144-11e5-ba71-058fbc01cf0b', Decimal('5.0000'), 10, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdbef330-7144-11e5-ba71-058fbc01cf0b', 'ce984d2c-7144-11e5-ba71-058fbc01cf0b', Decimal('4.5385'), 13, 'Havanese', 'Toy', 'Pure Breed'),
 ('fdc0518a-7144-11e5-ba71-058fbc01cf0b', 'ce99661c-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7333'), 15, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd684cf6-7144-11e5-ba71-058fbc01cf0b', 'ce473856-7144-11e5-ba71-058fbc01cf0b', Decimal('3.7222'), 18, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdbf66e4-7144-11e5-ba71-058fbc01cf0b', 'ce98b9b0-7144-11e5-ba71-058fbc01cf0b', Decimal('3.5000'), 14, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdc09b0e-7144-11e5-ba71-058fbc01cf0b', 'ce99bb76-7144-11e5-ba71-058fbc01cf0b', Decimal('3.2308'), 13, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdbeedc2-7144-11e5-ba71-058fbc01cf0b', 'ce9847dc-7144-11e5-ba71-058fbc01cf0b', Decimal('3.1538'), 13, 'Eurasier', None, 'Pure Breed'),
 ('fdc180be-7144-11e5-ba71-058fbc01cf0b', 'ce9a7110-7144-11e5-ba71-058fbc01cf0b', Decimal('3.0625'), 16, 'Chihuahua-Dachshund Mix', None, 'Cross Breed'),
 ('fd6aabd6-7144-11e5-ba71-058fbc01cf0b', 'ce6cd804-7144-11e5-ba71-058fbc01cf0b', Decimal('3.0000'), 13, 'American Pit Bull Terrier', None, 'Pure Breed'),
 ('fdbfc0b2-7144-11e5-ba71-058fbc01cf0b', 'ce98f3bc-7144-11e5-ba71-058fbc01cf0b', Decimal('2.6923'), 13, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbedef4-7144-11e5-ba71-058fbc01cf0b', 'ce982e46-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4615'), 13, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbec8ce-7144-11e5-ba71-058fbc01cf0b', 'ce980e3e-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4545'), 11, 'Basset Hound', 'Hound', 'Pure Breed'),
 ('fdbeff06-7144-11e5-ba71-058fbc01cf0b', 'ce9856f0-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4000'), 10, 'Bearded Collie', 'Herding', 'Pure Breed'),
 ('fdbfe22c-7144-11e5-ba71-058fbc01cf0b', 'ce99049c-7144-11e5-ba71-058fbc01cf0b', Decimal('2.4000'), 10, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdbed7ce-7144-11e5-ba71-058fbc01cf0b', 'ce981dc0-7144-11e5-ba71-058fbc01cf0b', Decimal('2.3333'), 18, 'Havanese', 'Toy', 'Pure Breed'),
 ('fdc1c31c-7144-11e5-ba71-058fbc01cf0b', 'ce9ac674-7144-11e5-ba71-058fbc01cf0b', Decimal('2.3077'), 13, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc0c49e-7144-11e5-ba71-058fbc01cf0b', 'ce99d674-7144-11e5-ba71-058fbc01cf0b', Decimal('2.2778'), 18, 'Other', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc19b30-7144-11e5-ba71-058fbc01cf0b', 'ce9aab30-7144-11e5-ba71-058fbc01cf0b', Decimal('2.2222'), 18, 'Brittany', 'Sporting', 'Pure Breed'),
 ('fdbedf94-7144-11e5-ba71-058fbc01cf0b', 'ce982ed2-7144-11e5-ba71-058fbc01cf0b', Decimal('2.0000'), 11, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0c502-7144-11e5-ba71-058fbc01cf0b', 'ce99d732-7144-11e5-ba71-058fbc01cf0b', Decimal('2.0000'), 15, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdbfddfe-7144-11e5-ba71-058fbc01cf0b', 'ce99049c-7144-11e5-ba71-058fbc01cf0b', Decimal('1.9375'), 16, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fd7104ae-7144-11e5-ba71-058fbc01cf0b', 'ce7212a6-7144-11e5-ba71-058fbc01cf0b', Decimal('1.9000'), 10, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc198d8-7144-11e5-ba71-058fbc01cf0b', 'ce9a9500-7144-11e5-ba71-058fbc01cf0b', Decimal('1.8000'), 10, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fdbe923c-7144-11e5-ba71-058fbc01cf0b', 'ce97f926-7144-11e5-ba71-058fbc01cf0b', Decimal('1.7647'), 17, 'Beagle', 'Hound', 'Pure Breed'),
 ('fd6a7490-7144-11e5-ba71-058fbc01cf0b', 'ce6cf3fc-7144-11e5-ba71-058fbc01cf0b', Decimal('1.7500'), 20, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdbef5e2-7144-11e5-ba71-058fbc01cf0b', 'ce984f70-7144-11e5-ba71-058fbc01cf0b', Decimal

The query should execute quickly.  This would NOT have been the case if you did not include the WHERE clause to combine the two tables. If you accidentally request a Cartesian product from datasets with billions of rows, you could be waiting for your query output for days (and will probably get in trouble with your database administrator).  <mark>So always remember to tell the database how to join your tables!</mark>

Let's examine our joined table a bit further.  The joined table outputted by the query above should have 38 rows, despite the fact that we set our LIMIT at 200.  The reason for this is that it turns out that a relatively small number of customers provided 10 or more reviews.  If you remove the HAVING and LIMIT BY clause from the query, you should end up with 389 rows.  **Go ahead and try it:**


In [9]:
%%sql
SELECT d.dog_guid AS DogID, d.user_guid AS UserID, AVG(r.rating) AS AvgRating,
COUNT(r.rating) AS NumRatings, d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid = r.dog_guid AND d.user_guid = r.user_guid
GROUP BY UserID, DogID, d.breed, d.breed_group, d.breed_type
ORDER BY AvgRating DESC;

395 rows affected.


[('fdbedd14-7144-11e5-ba71-058fbc01cf0b', 'ce975994-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf94de-7144-11e5-ba71-058fbc01cf0b', 'ce98cc34-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 2, 'Pembroke Welsh Corgi', 'Herding', 'Pure Breed'),
 ('fdbf178e-7144-11e5-ba71-058fbc01cf0b', 'ce986546-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Airedale Terrier', 'Terrier', 'Pure Breed'),
 ('fdc057ac-7144-11e5-ba71-058fbc01cf0b', 'ce996b9e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc121dc-7144-11e5-ba71-058fbc01cf0b', 'ce9a310a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc19554-7144-11e5-ba71-058fbc01cf0b', 'ce9a8a24-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc147ac-7144-11e5-ba71-058fbc01cf0b', 'ce9a545a-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Tibetan Terrier', 'Non-Sporting', 'Pure Breed'),
 ('fdc1c880-7144-11e5-ba71-058fbc01cf0b', 'ce96c768-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Maltese', 'Toy', 'Pure Breed'),
 ('fdc059fa-7144-11e5-ba71-058fbc01cf0b', 'ce996dc4-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Irish Water Spaniel', 'Sporting', 'Pure Breed'),
 ('fdc019c2-7144-11e5-ba71-058fbc01cf0b', 'ce99489e-7144-11e5-ba71-058fbc01cf0b', Decimal('9.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd41bca8-7144-11e5-ba71-058fbc01cf0b', 'ce7b055a-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 1, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdbf39f8-7144-11e5-ba71-058fbc01cf0b', 'ce987914-7144-11e5-ba71-058fbc01cf0b', Decimal('8.0000'), 12, 'Canaan Dog', 'Herding', 'Pure Breed'),
 ('fdc1e1a8-7144-11e5-ba71-058fbc01cf0b', 'ce9ad934-7144-11e5-ba71-058fbc01cf0b', Decimal('7.5000'), 2, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbe7a40-7144-11e5-ba71-058fbc01cf0b', 'ce97df9a-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 6, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbe8774-7144-11e5-ba71-058fbc01cf0b', 'ce97ebfc-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 4, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdbf940c-7144-11e5-ba71-058fbc01cf0b', 'ce98cb80-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Soft Coated Wheaten Terrier', 'Terrier', 'Pure Breed'),
 ('fdc1baca-7144-11e5-ba71-058fbc01cf0b', 'ce9ac2fa-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Poodle-Miniature Schnauzer Mix', None, 'Cross Breed'),
 ('fdc2417a-7144-11e5-ba71-058fbc01cf0b', 'ce9b35e6-7144-11e5-ba71-058fbc01cf0b', Decimal('7.0000'), 1, 'Bichon Frise', 'Non-Sporting', 'Pure Breed'),
 ('fdc1706a-7144-11e5-ba71-058fbc01cf0b', 'ce9a6846-7144-11e5-ba71-058fbc01cf0b', Decimal('6.8000'), 5, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0c2aa-7144-11e5-ba71-058fbc01cf0b', 'ce99d322-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Border Collie', 'Herding', 'Pure Breed'),
 ('fdbf8598-7144-11e5-ba71-058fbc01cf0b', 'ce98c46e-7144-11e5-ba71-058fbc01cf0b', Decimal('6.5000'), 2, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fd442826-7144-11e5-ba71-058fbc01cf0b', 'ce275612-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbee278-7144-11e5-ba71-058fbc01cf0b', 'ce9782c0-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdc00f86-7144-11e5-ba71-058fbc01cf0b', 'ce993b6a-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Yorkshire Terrier', 'Toy', 'Pure Breed'),
 ('fdbef2cc-7144-11e5-ba71-058fbc01cf0b', 'ce9838c8-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Labradoodle', None, 'Popular Hybrid'),
 ('fdc01f76-7144-11e5-ba71-058fbc01cf0b', 'ce994f1a-7144-11e5-ba71-058fbc01cf0b', Decimal('6.0000'), 1, 'Golden Doodle', None, 'Popular Hybrid'),
 ('fdc0345c-7144-11e5-ba71-058fbc01cf0b', 'ce99

It's clear from looking at this output that (A) not many customers provided ratings, and (B) when they did, they usually were not very surprised by their dog's performance.  Therefore, these ratings are probably not going to provide a lot of instructive insight into how to improve Dognition's completion rate.  However, the ratings table still provides a great opportunity to illustrate the results of different types of joins.  

To help prepare us for this:

**Questions 1-4:  How many unique dog_guids and user_guids are there in the reviews and dogs table independently?**  

In [13]:
%%sql
SELECT COUNT(DISTINCT dog_guid) AS Nums_DogID_From_Review
FROM reviews

1 rows affected.


[(5991,)]

In [14]:
%%sql
SELECT COUNT(DISTINCT dog_guid) AS Nums_DogID_From_dog
FROM dogs

1 rows affected.


[(35050,)]

In [15]:
%%sql
SELECT COUNT(DISTINCT user_guid) AS Nums_UserID_From_Review
FROM reviews

1 rows affected.


[(5586,)]

In [16]:
%%sql
SELECT COUNT(DISTINCT user_guid) AS Nums_UserID_From_dogs
FROM dogs

1 rows affected.


[(30967,)]

These counts indicate some important things:

+ Many customers in both the reviews and the dogs table have multiple dogs
+ There are many more unique dog_guids and user_guids in the dogs table than the reviews table
+ There are many more unique dog_guids and user_guids in the reviews table than in the output of our inner join

Let's test one more thing.  
   
**Try the inner join query once with just the dog_guid or once with just the user_guid clause in the WHERE statement:**



In [19]:
%%sql
SELECT d.dog_guid AS dogID, d.user_guid AS UserID, 
AVG(r.rating) AS AvgRating, COUNT(r.rating) AS NumRating,
d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.dog_guid = r.dog_guid
GROUP BY d.user_guid
ORDER BY AvgRating

389 rows affected.


[('fdbf56c2-7144-11e5-ba71-058fbc01cf0b', 'ce988eea-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Tibetan Terrier', 'Non-Sporting', 'Pure Breed'),
 ('fdbf55fa-7144-11e5-ba71-058fbc01cf0b', 'ce986708-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Poodle', 'Non-Sporting', 'Pure Breed'),
 ('fdc20a0c-7144-11e5-ba71-058fbc01cf0b', 'ce9b001c-7144-11e5-ba71-058fbc01cf0b', None, 0, 'French Bulldog', 'Non-Sporting', 'Pure Breed'),
 ('fdbeec32-7144-11e5-ba71-058fbc01cf0b', 'ce9846ba-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc1fddc-7144-11e5-ba71-058fbc01cf0b', 'ce88940e-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc02034-7144-11e5-ba71-058fbc01cf0b', 'ce995118-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Australian Shepherd', 'Herding', 'Pure Breed'),
 ('fdbf762a-7144-11e5-ba71-058fbc01cf0b', 'ce98c176-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Border Collie', 'Herding', 'Pure Breed'),
 ('fdc06454-7144-11e5-ba71-058fbc01cf0b', 'ce9978dc-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Portuguese Water Dog', 'Working', 'Pure Breed'),
 ('fdbfcc06-7144-11e5-ba71-058fbc01cf0b', 'ce98ff38-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc178ee-7144-11e5-ba71-058fbc01cf0b', 'ce9a6972-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdc0cf52-7144-11e5-ba71-058fbc01cf0b', 'ce99de30-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Great Dane-Bullmastiff Mix', None, 'Cross Breed'),
 ('fdbfc972-7144-11e5-ba71-058fbc01cf0b', 'ce98fa38-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf4588-7144-11e5-ba71-058fbc01cf0b', 'ce97e166-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fdc18be0-7144-11e5-ba71-058fbc01cf0b', 'ce9a7ebc-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Labrador Retriever-Border Collie Mix', None, 'Cross Breed'),
 ('fdc025de-7144-11e5-ba71-058fbc01cf0b', 'ce9955aa-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd45992c-7144-11e5-ba71-058fbc01cf0b', 'ce287fba-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Black Russian Terrier', 'Working', 'Pure Breed'),
 ('fdc0be5e-7144-11e5-ba71-058fbc01cf0b', 'ce99cbe8-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Boston Terrier', 'Non-Sporting', 'Pure Breed'),
 ('fd6a72e2-7144-11e5-ba71-058fbc01cf0b', 'ce6cf370-7144-11e5-ba71-058fbc01cf0b', None, 0, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fdbf320a-7144-11e5-ba71-058fbc01cf0b', 'ce9871c6-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Cocker Spaniel-Bichon Frise Mix', None, 'Cross Breed'),
 ('fdc001d0-7144-11e5-ba71-058fbc01cf0b', 'ce9932a0-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Jack Russell Terrier', 'Terrier', 'Pure Breed'),
 ('fdbef07e-7144-11e5-ba71-058fbc01cf0b', 'ce984a84-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Chesapeake Bay Retriever-Labrador Retriever Mix', None, 'Cross Breed'),
 ('fdc01530-7144-11e5-ba71-058fbc01cf0b', 'ce994204-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbef9c0-7144-11e5-ba71-058fbc01cf0b', 'ce985330-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Miniature Pinscher', 'Toy', 'Pure Breed'),
 ('fdbe7630-7144-11e5-ba71-058fbc01cf0b', 'ce97de1e-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Rhodesian Ridgeback', 'Hound', 'Pure Breed'),
 ('fdc1f940-7144-11e5-ba71-058fbc01cf0b', 'ce9aec80-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf0e88-7144-11e5-ba71-058fbc01cf0b', 'ce9862da-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdbf0aaa-7144-11e5-ba71-058fbc01cf0b', 'ce986154-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbf578a-7144-11e5-ba71-058fbc01cf0b', 'ce9894da-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Poodle-Golden Retriever Mix', None, 'Cross Breed'),
 ('fdbf3070-7144-11e5-

In [20]:
%%sql
SELECT d.dog_guid AS dogID, d.user_guid AS UserID, 
AVG(r.rating) AS AvgRating, COUNT(r.rating) AS NumRating,
d.breed, d.breed_group, d.breed_type
FROM dogs d, reviews r
WHERE d.user_guid = r.user_guid
GROUP BY d.user_guid
ORDER BY AvgRating

5586 rows affected.


[('fd70167a-7144-11e5-ba71-058fbc01cf0b', 'ce712b20-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Pug', 'Toy', 'Pure Breed'),
 ('fdac1422-7144-11e5-ba71-058fbc01cf0b', 'ce8284d8-7144-11e5-ba71-058fbc01cf0b', None, 0, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fd76d35c-7144-11e5-ba71-058fbc01cf0b', 'ce770694-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Australian Shepherd', 'Herding', 'Pure Breed'),
 ('fd6c8744-7144-11e5-ba71-058fbc01cf0b', 'ce6e201a-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd41b7e4-7144-11e5-ba71-058fbc01cf0b', 'ce254534-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Portuguese Water Dog', 'Working', 'Pure Breed'),
 ('fdadd604-7144-11e5-ba71-058fbc01cf0b', 'ce840db2-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdac2a52-7144-11e5-ba71-058fbc01cf0b', 'ce828b22-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Cockapoo', None, 'Popular Hybrid'),
 ('fd6fb39c-7144-11e5-ba71-058fbc01cf0b', 'ce70dd14-7144-11e5-ba71-058fbc01cf0b', None, 0, 'American Eskimo Dog-Chihuahua Mix', None, 'Cross Breed'),
 ('fdba23fa-7144-11e5-ba71-058fbc01cf0b', 'ce951a30-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Poodle', 'Non-Sporting', 'Pure Breed'),
 ('fd7732fc-7144-11e5-ba71-058fbc01cf0b', 'ce776e68-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Beagle', 'Hound', 'Pure Breed'),
 ('fdc02034-7144-11e5-ba71-058fbc01cf0b', 'ce995118-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Australian Shepherd', 'Herding', 'Pure Breed'),
 ('fd69f060-7144-11e5-ba71-058fbc01cf0b', 'ce6c3250-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd71e432-7144-11e5-ba71-058fbc01cf0b', 'ce72d15a-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Cane Corso', 'Working', 'Pure Breed'),
 ('fd51b784-7144-11e5-ba71-058fbc01cf0b', 'ce32e0ea-7144-11e5-ba71-058fbc01cf0b', None, 0, 'English Springer Spaniel', 'Sporting', 'Pure Breed'),
 ('fd728298-7144-11e5-ba71-058fbc01cf0b', 'ce734d2e-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fd73f394-7144-11e5-ba71-058fbc01cf0b', 'ce746c7c-7144-11e5-ba71-058fbc01cf0b', None, 0, 'American Eskimo Dog', 'Non-Sporting', 'Pure Breed'),
 ('fdad781c-7144-11e5-ba71-058fbc01cf0b', 'ce83b830-7144-11e5-ba71-058fbc01cf0b', None, 0, 'American Staffordshire Terrier-Dogue de Bordeaux Mix', None, 'Cross Breed'),
 ('fd6d049e-7144-11e5-ba71-058fbc01cf0b', 'ce6e869a-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Papillon', 'Toy', 'Pure Breed'),
 ('fd6e086c-7144-11e5-ba71-058fbc01cf0b', 'ce6f6812-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fdba7d3c-7144-11e5-ba71-058fbc01cf0b', 'ce957a0c-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('fd7cc6ea-7144-11e5-ba71-058fbc01cf0b', 'ce7bd3b8-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('fdbb0fd6-7144-11e5-ba71-058fbc01cf0b', 'ce960cc4-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Collie', 'Herding', 'Pure Breed'),
 ('fd6dd658-7144-11e5-ba71-058fbc01cf0b', 'ce6f4346-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Cockapoo', None, 'Popular Hybrid'),
 ('fdac534c-7144-11e5-ba71-058fbc01cf0b', 'ce826958-7144-11e5-ba71-058fbc01cf0b', None, 0, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('fd7bc5f6-7144-11e5-ba71-058fbc01cf0b', 'ce7b5e06-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Vizsla', 'Sporting', 'Pure Breed'),
 ('fd678e9c-7144-11e5-ba71-058fbc01cf0b', 'ce418258-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Labrador Retriever-Golden Retriever Mix', None, 'Cross Breed'),
 ('fdac42bc-7144-11e5-ba71-058fbc01cf0b', 'ce82a382-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('fd816f92-7144-11e5-ba71-058fbc01cf0b', 'ce7de5e0-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Chihuahua', 'Toy', 'Pure Breed'),
 ('fdbe7630-7144-11e5-ba71-058fbc01cf0b', 'ce97de1e-7144-11e5-ba71-058fbc01cf0b', None, 0, 'Rhodesian Ridgeback', 'Hound', 'Pure Breed'),

When you run the query by joining on the dog_guid only, you still get 389 rows in your output.  When you run the query by joining on the user_guid only, you get 5586 rows in your output.  This means that:

+ All of the user_guids in the reviews table are in the dogs table
+ Only 389 of the over 5000 dog_guids in the reviews table are in the dogs table

Perhaps most importantly for our current purposes, these COUNT queries show you that <mark>*inner joins only output the data from rows that have equivalent values in both tables being joined*.</mark>  If you wanted to include all the dog_guids or user_guids in one or both of the tables, you would have to use an outer join, which we will practice in the next lesson.

Try an inner join on your own.  
   

**Question 5: How would you extract the user_guid, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game (you should get 20,845 rows if you join on dog_guid only)?**

In [6]:
%%sql
SELECT c.test_name AS TestName, 
c.dog_guid AS dogID, c.user_guid AS UserID, 
d.breed, d.breed_group, d.breed_type
FROM dogs d,complete_tests c
WHERE d.dog_guid = c.dog_guid AND c.test_name = 'Yawn Warm-up';


20845 rows affected.


[('Yawn Warm-up', 'fd27b272-7144-11e5-ba71-058fbc01cf0b', None, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27b5ba-7144-11e5-ba71-058fbc01cf0b', None, 'Shetland Sheepdog', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', None, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', None, 'Golden Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27b86c-7144-11e5-ba71-058fbc01cf0b', None, 'Shih Tzu', 'Toy', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27b948-7144-11e5-ba71-058fbc01cf0b', None, 'Siberian Husky', 'Working', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27ba1a-7144-11e5-ba71-058fbc01cf0b', None, 'Shih Tzu', 'Toy', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27bbbe-7144-11e5-ba71-058fbc01cf0b', None, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('Yawn Warm-up', 'fd27c1c2-7144-11e5-ba71-058fbc01cf0b', None, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27c5be-7144-11e5-ba71-058fbc01cf0b', None, 'Shih Tzu-Poodle Mix', None, 'Cross Breed'),
 ('Yawn Warm-up', 'fd27c74e-7144-11e5-ba71-058fbc01cf0b', None, 'German Shepherd Dog-Pembroke Welsh Corgi Mix', None, 'Cross Breed'),
 ('Yawn Warm-up', 'fd27c7d0-7144-11e5-ba71-058fbc01cf0b', None, 'Vizsla', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27c852-7144-11e5-ba71-058fbc01cf0b', None, 'Pug', 'Toy', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27c8d4-7144-11e5-ba71-058fbc01cf0b', None, 'Boxer', 'Working', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27c956-7144-11e5-ba71-058fbc01cf0b', None, 'German Shepherd Dog-Nova Scotia Duck Tolling Retriever Mix', None, 'Cross Breed'),
 ('Yawn Warm-up', 'fd27cb72-7144-11e5-ba71-058fbc01cf0b', None, 'Beagle', 'Hound', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27cd98-7144-11e5-ba71-058fbc01cf0b', None, 'Beagle', 'Hound', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27ce1a-7144-11e5-ba71-058fbc01cf0b', None, 'Beagle', 'Hound', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27cea6-7144-11e5-ba71-058fbc01cf0b', None, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('Yawn Warm-up', 'fd27cf28-7144-11e5-ba71-058fbc01cf0b', None, 'Chesapeake Bay Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27cfaa-7144-11e5-ba71-058fbc01cf0b', None, 'Border Collie', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d02c-7144-11e5-ba71-058fbc01cf0b', None, 'Belgian Malinois', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d0b8-7144-11e5-ba71-058fbc01cf0b', None, 'Australian Shepherd-German Shepherd Dog Mix', None, 'Cross Breed'),
 ('Yawn Warm-up', 'fd27d144-7144-11e5-ba71-058fbc01cf0b', None, 'Poodle', 'Non-Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d1c6-7144-11e5-ba71-058fbc01cf0b', None, 'Poodle', 'Non-Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d248-7144-11e5-ba71-058fbc01cf0b', None, 'Golden Doodle', None, 'Popular Hybrid'),
 ('Yawn Warm-up', 'fd27d2ca-7144-11e5-ba71-058fbc01cf0b', None, 'Labrador Retriever', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d34c-7144-11e5-ba71-058fbc01cf0b', None, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d3d8-7144-11e5-ba71-058fbc01cf0b', None, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d45a-7144-11e5-ba71-058fbc01cf0b', None, 'Weimaraner', 'Sporting', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d4dc-7144-11e5-ba71-058fbc01cf0b', None, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('Yawn Warm-up', 'fd27d770-7144-11e5-ba71-058fbc01cf0b', None, 'Bouvier des Flandres', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27d9fa-7144-11e5-ba71-058fbc01cf0b', None, 'Mixed', None, "Mixed Breed/ Other/ I Don't Know"),
 ('Yawn Warm-up', 'fd27db08-7144-11e5-ba71-058fbc01cf0b', None, 'German Shepherd Dog', 'Herding', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27db8a-7144-11e5-ba71-058fbc01cf0b', None, 'Beagle', 'Hound', 'Pure Breed'),
 ('Yawn Warm-up', 'fd27dc52-7144-11e5-ba71-058fbc01cf0b', None, 'Mudi', None, 'Pure Breed'),
 ('Yawn Warm-up', 'fd27dd38-7144-11e5-ba71-058fb

## 2. Joining More than 2 Tables

In theory, you can join as many tables together as you want or need.  To join multiple tables you take the same approach as we took when we were joining two tables together: list all the fields you want to extract in the SELECT statement, specify which table they came from in the SELECT statement, list all the tables from which you will need to extract the fields in the FROM statement, and then tell the database how to connect the tables in the WHERE statement.

To extract the user_guid, user's state of residence, user's zip code, dog_guid, breed, breed_type, and breed_group for all animals who completed the "Yawn Warm-up" game, you might be tempted to query:

```mySQL
SELECT c.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND c.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```
This query focuses the relationships primarily on the complete_tests table.  However, it turns out that our Dognition dataset has only NULL values in the user_guid column of the complete_tests table.  If you were to execute the query above, you would not get an error message, but your output would have 0 rows.  However, the power of relational databases will come in handy here.  You can use the dogs table to link the complete_tests and users table (pay attention to the difference between the WHERE statement in this query vs. the WHERE statement in the query above):

```mySQL
SELECT d.user_guid AS UserID, u.state, u.zip, d.dog_guid AS DogID, d.breed, d.breed_type, d.breed_group
FROM dogs d, complete_tests c, users u
WHERE d.dog_guid=c.dog_guid 
   AND d.user_guid=u.user_guid
   AND c.test_name="Yawn Warm-up";
```

Of note, joins are very resource intensive, so try not to join unnecessarily.  In general, the more joins you have to execute, the slower your query performance will be.

**Question 6: How would you extract the user_guid, membership_type, and dog_guid of all the golden retrievers who completed at least 1 Dognition test (you should get 711 rows)?**

In [10]:
%%sql
SELECT DISTINCT d.user_guid, d.dog_guid, 
u.membership_type, d.breed
FROM users u, complete_tests c, dogs d
WHERE d.user_guid = u.user_guid 
AND c.dog_guid = d.dog_guid
AND d.breed = 'Golden Retriever'

711 rows affected.


[('ce135ab8-7144-11e5-ba71-058fbc01cf0b', 'fd27b6b4-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce13507c-7144-11e5-ba71-058fbc01cf0b', 'fd27b79a-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce1389d4-7144-11e5-ba71-058fbc01cf0b', 'fd27efb2-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce21f122-7144-11e5-ba71-058fbc01cf0b', 'fd3d03fc-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce220bb2-7144-11e5-ba71-058fbc01cf0b', 'fd3d10cc-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce2237f4-7144-11e5-ba71-058fbc01cf0b', 'fd3d3b24-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce2243e8-7144-11e5-ba71-058fbc01cf0b', 'fd3d4b8c-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce240b24-7144-11e5-ba71-058fbc01cf0b', 'fd3fe96e-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce135cf2-7144-11e5-ba71-058fbc01cf0b', 'fd7af63a-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24476a-7144-11e5-ba71-058fbc01cf0b', 'fd404ff8-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce245cdc-7144-11e5-ba71-058fbc01cf0b', 'fd4059e4-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce245cdc-7144-11e5-ba71-058fbc01cf0b', 'fd45eb98-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce246be6-7144-11e5-ba71-058fbc01cf0b', 'fd40738e-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce246be6-7144-11e5-ba71-058fbc01cf0b', 'fd45d6ee-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce249774-7144-11e5-ba71-058fbc01cf0b', 'fd408ed2-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce249c6a-7144-11e5-ba71-058fbc01cf0b', 'fd40945e-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce2258a6-7144-11e5-ba71-058fbc01cf0b', 'fd6487c4-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24c1c2-7144-11e5-ba71-058fbc01cf0b', 'fd40ee72-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24a106-7144-11e5-ba71-058fbc01cf0b', 'fd40f822-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24d572-7144-11e5-ba71-058fbc01cf0b', 'fd4107cc-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24d914-7144-11e5-ba71-058fbc01cf0b', 'fd410cb8-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce24de50-7144-11e5-ba71-058fbc01cf0b', 'fd411690-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce24e116-7144-11e5-ba71-058fbc01cf0b', 'fd4118e8-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce24e684-7144-11e5-ba71-058fbc01cf0b', 'fd411b0e-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce253a6c-7144-11e5-ba71-058fbc01cf0b', 'fd418b02-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce2556a0-7144-11e5-ba71-058fbc01cf0b', 'fd41c5f4-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce255c54-7144-11e5-ba71-058fbc01cf0b', 'fd41c84c-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce257fc2-7144-11e5-ba71-058fbc01cf0b', 'fd41db34-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce2585a8-7144-11e5-ba71-058fbc01cf0b', 'fd41e232-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce22680a-7144-11e5-ba71-058fbc01cf0b', 'fd41e28c-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce258a08-7144-11e5-ba71-058fbc01cf0b', 'fd41e796-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce259dd6-7144-11e5-ba71-058fbc01cf0b', 'fd421400-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce25c306-7144-11e5-ba71-058fbc01cf0b', 'fd423f70-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce25caa4-7144-11e5-ba71-058fbc01cf0b', 'fd4244f2-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce25f4de-7144-11e5-ba71-058fbc01cf0b', 'fd4275a8-7144-11e5-ba71-058fbc01cf0b', 2, 'Golden Retriever'),
 ('ce26092e-7144-11e5-ba71-058fbc01cf0b', 'fd42933a-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce261a40-7144-11e5-ba71-058fbc01cf0b', 'fd42a29e-7144-11e5-ba71-058fbc01cf0b', 1, 'Golden Retriever'),
 ('ce261bd0-7144-11e5-ba71-058fbc01cf0b', 'fd42a366-7144-11e5-ba71-058fbc01cf0

## Practice inner joining your own tables!

**Question 7: How many unique Golden Retrievers who live in North Carolina are there in the Dognition database (you should get 30)?**



In [13]:
%%sql
SELECT COUNT(DISTINCT d.dog_guid), u.state, d.breed
FROM users u, dogs d
WHERE u.user_guid = d.user_guid 
AND d.breed = 'Golden Retriever'
AND u.state = 'NC'


1 rows affected.


[(30, 'NC', 'Golden Retriever')]

**Question 8: How many unique customers within each membership type provided reviews (there should be 2900 in the membership type with the greatest number of customers, and 15 in the membership type with the fewest number of customers if you do NOT include entries with NULL values in their ratings field)?**

In [14]:
%%sql
SELECT COUNT(DISTINCT u.user_guid) AS Num_user, 
u.membership_type
FROM users u, reviews r
WHERE u.user_guid = r.user_guid
GROUP BY u.membership_type
ORDER BY Num_user DESC

5 rows affected.


[(3208, 1), (1226, 2), (875, 4), (259, 3), (18, 5)]

**Question 9: For which 3 dog breeds do we have the greatest amount of site_activity data, (as defined by non-NULL values in script_detail_id)(your answers should be "Mixed", "Labrador Retriever", and "Labrador Retriever-Golden Retriever Mix"?**

In [15]:
%%sql
SELECT d.breed, COUNT(s.script_detail_id) AS num_act
FROM dogs d,site_activities s

WHERE s.dog_guid = d.dog_guid AND s.script_detail_id IS NOT NULL
GROUP BY d.breed
ORDER BY num_act DESC
LIMIT 3;

3 rows affected.


[('Mixed', 93415),
 ('Labrador Retriever', 38804),
 ('Labrador Retriever-Golden Retriever Mix', 27498)]

**Practice any other inner joins you would like to try here!**

In [18]:
%%sql
SELECT COUNT(DISTINCT d.dog_guid) AS Num_Dogs, u.state, d.breed
FROM users u, dogs d
WHERE u.user_guid = d.user_guid 
AND d.breed = 'Shiba Inu'
GROUP BY u.state


20 rows affected.


[(44, None, 'Shiba Inu'),
 (1, '0', 'Shiba Inu'),
 (1, 'AB', 'Shiba Inu'),
 (1, 'BY', 'Shiba Inu'),
 (10, 'CA', 'Shiba Inu'),
 (3, 'CO', 'Shiba Inu'),
 (1, 'DEV', 'Shiba Inu'),
 (1, 'GA', 'Shiba Inu'),
 (1, 'IL', 'Shiba Inu'),
 (1, 'MA', 'Shiba Inu'),
 (1, 'MD', 'Shiba Inu'),
 (1, 'MI', 'Shiba Inu'),
 (28, 'N/A', 'Shiba Inu'),
 (2, 'NC', 'Shiba Inu'),
 (1, 'NJ', 'Shiba Inu'),
 (1, 'NY', 'Shiba Inu'),
 (1, 'ON', 'Shiba Inu'),
 (1, 'PA', 'Shiba Inu'),
 (2, 'TX', 'Shiba Inu'),
 (1, 'WA', 'Shiba Inu')]